[package]
name = "money-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.6"
pest_derive = "2.6"
wasm-bindgen = "0.2.88"
serde-wasm-bindgen = "0.6.1"
thiserror = "1.0.50"
